package dns

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"strings"
	"text/template"

	"dpi-kyrsach/internal/runner"
)

const dnsmasqTemplate = `# Generated by dpi-kyrsach. Manual edits will be overwritten.
{{- range . }}
address=/{{ . }}/0.0.0.0
{{- end }}
`

// Service manages dnsmasq blocklist config and reload command.
type Service struct {
	Runner        runner.CommandRunner
	ConfigPath    string
	ReloadCommand []string
}

func NewService(r runner.CommandRunner, configPath string, reloadCommand []string) Service {
	return Service{
		Runner:        r,
		ConfigPath:    configPath,
		ReloadCommand: reloadCommand,
	}
}

// Apply writes dnsmasq config and reloads dnsmasq.
func (s Service) Apply(ctx context.Context, blockedDomains []string) error {
	if strings.TrimSpace(s.ConfigPath) == "" {
		return fmt.Errorf("dns config path must not be empty")
	}

	content, err := RenderConfig(blockedDomains)
	if err != nil {
		return fmt.Errorf("render dnsmasq config: %w", err)
	}
	if err := os.WriteFile(s.ConfigPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write dnsmasq config: %w", err)
	}

	if len(s.ReloadCommand) == 0 || s.Runner == nil {
		return nil
	}

	_, err = s.Runner.Run(ctx, s.ReloadCommand[0], s.ReloadCommand[1:]...)
	if err != nil {
		return fmt.Errorf("reload dnsmasq: %w", err)
	}

	return nil
}

// RenderConfig returns dnsmasq blocklist config content.
func RenderConfig(blockedDomains []string) (string, error) {
	tmpl, err := template.New("dnsmasq").Parse(dnsmasqTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, normalizeDomains(blockedDomains)); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func normalizeDomains(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		domain := strings.ToLower(strings.TrimSpace(value))
		if domain == "" {
			continue
		}
		if _, ok := seen[domain]; ok {
			continue
		}
		seen[domain] = struct{}{}
		out = append(out, domain)
	}
	return out
}
